#!/usr/bin/env python3
"""Generate ``worlds/dynamic_daisy_chain_generated.wbt`` tunnel body + markers (seed-driven)."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "controllers" / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from tunnel_geometry import build_tunnel_geometry  # noqa: E402
from world_generator import tunnel_segment_solids, victim_markers  # noqa: E402
from target_discovery import spawn_victims  # noqa: E402
import random  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser(description="Write procedural tunnel VRML fragment / full world stub.")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out", type=Path, default=ROOT / "worlds" / "dynamic_daisy_chain_generated.wbt")
    args = ap.parse_args()
    rng = random.Random(args.seed)
    geom = build_tunnel_geometry(args.seed)
    victims = spawn_victims(geom, rng, 5)
    body = tunnel_segment_solids(geom) + "\n" + victim_markers(victims)
    header = f"""#VRML_SIM R2024a utf8
# Generated by scripts/generate_tunnel.py seed={args.seed}
EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots/R2024a/projects/objects/backgrounds/protos/TexturedBackground.proto"

WorldInfo {{
  title "Dynamic Daisy Chain — generated tunnel (seed {args.seed})"
  basicTimeStep 16
  FPS 60
}}
Viewpoint {{
  position 25 35 120
  orientation 0.06 0.99 0.12 3.45
}}
TexturedBackground {{ texture "dusk" }}
DirectionalLight {{
  direction 0.3 -1 0.2
  intensity 1.4
  castShadows TRUE
}}
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header + body, encoding="utf-8")
    print("Wrote", args.out)


if __name__ == "__main__":
    main()
