/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as VertexSwarmRouteImport } from './routes/vertex-swarm'
import { Route as VertexRouteImport } from './routes/vertex'
import { Route as Track2WebotsRouteImport } from './routes/track2-webots'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TashiRouteImport } from './routes/tashi'
import { Route as SwarmRouteImport } from './routes/swarm'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ScenariosWarehouseRestockingRouteImport } from './routes/scenarios.warehouse-restocking'
import { Route as ScenariosWarehouseRestockRouteImport } from './routes/scenarios.warehouse-restock'
import { Route as ScenariosThermalRebalanceRouteImport } from './routes/scenarios.thermal-rebalance'
import { Route as ScenariosStakeVotingRouteImport } from './routes/scenarios.stake-voting'
import { Route as ScenariosRandomFailureRouteImport } from './routes/scenarios.random-failure'
import { Route as ScenariosPredatorEvasionRouteImport } from './routes/scenarios.predator-evasion'
import { Route as ScenariosObstacleBypassRouteImport } from './routes/scenarios.obstacle-bypass'
import { Route as ScenariosMultiSwarmHandoffRouteImport } from './routes/scenarios.multi-swarm-handoff'
import { Route as ScenariosMagneticAttractionRouteImport } from './routes/scenarios.magnetic-attraction'
import { Route as ScenariosHandoffRouteImport } from './routes/scenarios.handoff'
import { Route as ScenariosFallenRouteImport } from './routes/scenarios.fallen'
import { Route as ScenariosDaisyRouteImport } from './routes/scenarios.daisy'
import { Route as ScenariosCollapsingTunnelRouteImport } from './routes/scenarios.collapsing-tunnel'
import { Route as ScenariosCircularBypassRouteImport } from './routes/scenarios.circular-bypass'
import { Route as ScenariosBlindHandoffRouteImport } from './routes/scenarios.blind-handoff'
import { Route as ScenariosBatteryCascadeRouteImport } from './routes/scenarios.battery-cascade'
import { Route as ScenariosArenaObstacleRouteImport } from './routes/scenarios.arena-obstacle'
import { Route as DronesIdRouteImport } from './routes/drones.$id'
import { Route as DroneIdRouteImport } from './routes/drone.$id'
import { Route as DashboardSplatRouteImport } from './routes/dashboard/$'
import { Route as ScenariosSearchRescueIndexRouteImport } from './routes/scenarios.search-rescue.index'
import { Route as ScenariosSearchRescueScenarioSlugRouteImport } from './routes/scenarios.search-rescue.$scenarioSlug'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const VertexSwarmRoute = VertexSwarmRouteImport.update({
  id: '/vertex-swarm',
  path: '/vertex-swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const VertexRoute = VertexRouteImport.update({
  id: '/vertex',
  path: '/vertex',
  getParentRoute: () => rootRouteImport,
} as any)
const Track2WebotsRoute = Track2WebotsRouteImport.update({
  id: '/track2-webots',
  path: '/track2-webots',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TashiRoute = TashiRouteImport.update({
  id: '/tashi',
  path: '/tashi',
  getParentRoute: () => rootRouteImport,
} as any)
const SwarmRoute = SwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosWarehouseRestockingRoute =
  ScenariosWarehouseRestockingRouteImport.update({
    id: '/scenarios/warehouse-restocking',
    path: '/scenarios/warehouse-restocking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosWarehouseRestockRoute =
  ScenariosWarehouseRestockRouteImport.update({
    id: '/scenarios/warehouse-restock',
    path: '/scenarios/warehouse-restock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosThermalRebalanceRoute =
  ScenariosThermalRebalanceRouteImport.update({
    id: '/scenarios/thermal-rebalance',
    path: '/scenarios/thermal-rebalance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosStakeVotingRoute = ScenariosStakeVotingRouteImport.update({
  id: '/scenarios/stake-voting',
  path: '/scenarios/stake-voting',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRandomFailureRoute = ScenariosRandomFailureRouteImport.update({
  id: '/scenarios/random-failure',
  path: '/scenarios/random-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosPredatorEvasionRoute =
  ScenariosPredatorEvasionRouteImport.update({
    id: '/scenarios/predator-evasion',
    path: '/scenarios/predator-evasion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosObstacleBypassRoute = ScenariosObstacleBypassRouteImport.update({
  id: '/scenarios/obstacle-bypass',
  path: '/scenarios/obstacle-bypass',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosMultiSwarmHandoffRoute =
  ScenariosMultiSwarmHandoffRouteImport.update({
    id: '/scenarios/multi-swarm-handoff',
    path: '/scenarios/multi-swarm-handoff',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosMagneticAttractionRoute =
  ScenariosMagneticAttractionRouteImport.update({
    id: '/scenarios/magnetic-attraction',
    path: '/scenarios/magnetic-attraction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosHandoffRoute = ScenariosHandoffRouteImport.update({
  id: '/scenarios/handoff',
  path: '/scenarios/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosFallenRoute = ScenariosFallenRouteImport.update({
  id: '/scenarios/fallen',
  path: '/scenarios/fallen',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosDaisyRoute = ScenariosDaisyRouteImport.update({
  id: '/scenarios/daisy',
  path: '/scenarios/daisy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosCollapsingTunnelRoute =
  ScenariosCollapsingTunnelRouteImport.update({
    id: '/scenarios/collapsing-tunnel',
    path: '/scenarios/collapsing-tunnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosCircularBypassRoute = ScenariosCircularBypassRouteImport.update({
  id: '/scenarios/circular-bypass',
  path: '/scenarios/circular-bypass',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosBlindHandoffRoute = ScenariosBlindHandoffRouteImport.update({
  id: '/scenarios/blind-handoff',
  path: '/scenarios/blind-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosBatteryCascadeRoute = ScenariosBatteryCascadeRouteImport.update({
  id: '/scenarios/battery-cascade',
  path: '/scenarios/battery-cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosArenaObstacleRoute = ScenariosArenaObstacleRouteImport.update({
  id: '/scenarios/arena-obstacle',
  path: '/scenarios/arena-obstacle',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesIdRoute = DronesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DronesRoute,
} as any)
const DroneIdRoute = DroneIdRouteImport.update({
  id: '/drone/$id',
  path: '/drone/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/dashboard/$',
  path: '/dashboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosSearchRescueIndexRoute =
  ScenariosSearchRescueIndexRouteImport.update({
    id: '/scenarios/search-rescue/',
    path: '/scenarios/search-rescue/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenariosSearchRescueScenarioSlugRoute =
  ScenariosSearchRescueScenarioSlugRouteImport.update({
    id: '/scenarios/search-rescue/$scenarioSlug',
    path: '/scenarios/search-rescue/$scenarioSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/drones': typeof DronesRouteWithChildren
  '/features': typeof FeaturesRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/network': typeof NetworkRoute
  '/replay': typeof ReplayRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/swarm': typeof SwarmRoute
  '/tashi': typeof TashiRoute
  '/tasks': typeof TasksRoute
  '/track2-webots': typeof Track2WebotsRoute
  '/vertex': typeof VertexRoute
  '/vertex-swarm': typeof VertexSwarmRoute
  '/worlds': typeof WorldsRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/drone/$id': typeof DroneIdRoute
  '/drones/$id': typeof DronesIdRoute
  '/scenarios/arena-obstacle': typeof ScenariosArenaObstacleRoute
  '/scenarios/battery-cascade': typeof ScenariosBatteryCascadeRoute
  '/scenarios/blind-handoff': typeof ScenariosBlindHandoffRoute
  '/scenarios/circular-bypass': typeof ScenariosCircularBypassRoute
  '/scenarios/collapsing-tunnel': typeof ScenariosCollapsingTunnelRoute
  '/scenarios/daisy': typeof ScenariosDaisyRoute
  '/scenarios/fallen': typeof ScenariosFallenRoute
  '/scenarios/handoff': typeof ScenariosHandoffRoute
  '/scenarios/magnetic-attraction': typeof ScenariosMagneticAttractionRoute
  '/scenarios/multi-swarm-handoff': typeof ScenariosMultiSwarmHandoffRoute
  '/scenarios/obstacle-bypass': typeof ScenariosObstacleBypassRoute
  '/scenarios/predator-evasion': typeof ScenariosPredatorEvasionRoute
  '/scenarios/random-failure': typeof ScenariosRandomFailureRoute
  '/scenarios/stake-voting': typeof ScenariosStakeVotingRoute
  '/scenarios/thermal-rebalance': typeof ScenariosThermalRebalanceRoute
  '/scenarios/warehouse-restock': typeof ScenariosWarehouseRestockRoute
  '/scenarios/warehouse-restocking': typeof ScenariosWarehouseRestockingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/scenarios/search-rescue/$scenarioSlug': typeof ScenariosSearchRescueScenarioSlugRoute
  '/scenarios/search-rescue/': typeof ScenariosSearchRescueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/drones': typeof DronesRouteWithChildren
  '/features': typeof FeaturesRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/network': typeof NetworkRoute
  '/replay': typeof ReplayRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/swarm': typeof SwarmRoute
  '/tashi': typeof TashiRoute
  '/tasks': typeof TasksRoute
  '/track2-webots': typeof Track2WebotsRoute
  '/vertex': typeof VertexRoute
  '/vertex-swarm': typeof VertexSwarmRoute
  '/worlds': typeof WorldsRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/drone/$id': typeof DroneIdRoute
  '/drones/$id': typeof DronesIdRoute
  '/scenarios/arena-obstacle': typeof ScenariosArenaObstacleRoute
  '/scenarios/battery-cascade': typeof ScenariosBatteryCascadeRoute
  '/scenarios/blind-handoff': typeof ScenariosBlindHandoffRoute
  '/scenarios/circular-bypass': typeof ScenariosCircularBypassRoute
  '/scenarios/collapsing-tunnel': typeof ScenariosCollapsingTunnelRoute
  '/scenarios/daisy': typeof ScenariosDaisyRoute
  '/scenarios/fallen': typeof ScenariosFallenRoute
  '/scenarios/handoff': typeof ScenariosHandoffRoute
  '/scenarios/magnetic-attraction': typeof ScenariosMagneticAttractionRoute
  '/scenarios/multi-swarm-handoff': typeof ScenariosMultiSwarmHandoffRoute
  '/scenarios/obstacle-bypass': typeof ScenariosObstacleBypassRoute
  '/scenarios/predator-evasion': typeof ScenariosPredatorEvasionRoute
  '/scenarios/random-failure': typeof ScenariosRandomFailureRoute
  '/scenarios/stake-voting': typeof ScenariosStakeVotingRoute
  '/scenarios/thermal-rebalance': typeof ScenariosThermalRebalanceRoute
  '/scenarios/warehouse-restock': typeof ScenariosWarehouseRestockRoute
  '/scenarios/warehouse-restocking': typeof ScenariosWarehouseRestockingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/scenarios/search-rescue/$scenarioSlug': typeof ScenariosSearchRescueScenarioSlugRoute
  '/scenarios/search-rescue': typeof ScenariosSearchRescueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRoute
  '/drones': typeof DronesRouteWithChildren
  '/features': typeof FeaturesRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/network': typeof NetworkRoute
  '/replay': typeof ReplayRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/swarm': typeof SwarmRoute
  '/tashi': typeof TashiRoute
  '/tasks': typeof TasksRoute
  '/track2-webots': typeof Track2WebotsRoute
  '/vertex': typeof VertexRoute
  '/vertex-swarm': typeof VertexSwarmRoute
  '/worlds': typeof WorldsRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/drone/$id': typeof DroneIdRoute
  '/drones/$id': typeof DronesIdRoute
  '/scenarios/arena-obstacle': typeof ScenariosArenaObstacleRoute
  '/scenarios/battery-cascade': typeof ScenariosBatteryCascadeRoute
  '/scenarios/blind-handoff': typeof ScenariosBlindHandoffRoute
  '/scenarios/circular-bypass': typeof ScenariosCircularBypassRoute
  '/scenarios/collapsing-tunnel': typeof ScenariosCollapsingTunnelRoute
  '/scenarios/daisy': typeof ScenariosDaisyRoute
  '/scenarios/fallen': typeof ScenariosFallenRoute
  '/scenarios/handoff': typeof ScenariosHandoffRoute
  '/scenarios/magnetic-attraction': typeof ScenariosMagneticAttractionRoute
  '/scenarios/multi-swarm-handoff': typeof ScenariosMultiSwarmHandoffRoute
  '/scenarios/obstacle-bypass': typeof ScenariosObstacleBypassRoute
  '/scenarios/predator-evasion': typeof ScenariosPredatorEvasionRoute
  '/scenarios/random-failure': typeof ScenariosRandomFailureRoute
  '/scenarios/stake-voting': typeof ScenariosStakeVotingRoute
  '/scenarios/thermal-rebalance': typeof ScenariosThermalRebalanceRoute
  '/scenarios/warehouse-restock': typeof ScenariosWarehouseRestockRoute
  '/scenarios/warehouse-restocking': typeof ScenariosWarehouseRestockingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/scenarios/search-rescue/$scenarioSlug': typeof ScenariosSearchRescueScenarioSlugRoute
  '/scenarios/search-rescue/': typeof ScenariosSearchRescueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/demo'
    | '/docs'
    | '/drones'
    | '/features'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/replay'
    | '/safety'
    | '/settings'
    | '/swarm'
    | '/tashi'
    | '/tasks'
    | '/track2-webots'
    | '/vertex'
    | '/vertex-swarm'
    | '/worlds'
    | '/dashboard/$'
    | '/drone/$id'
    | '/drones/$id'
    | '/scenarios/arena-obstacle'
    | '/scenarios/battery-cascade'
    | '/scenarios/blind-handoff'
    | '/scenarios/circular-bypass'
    | '/scenarios/collapsing-tunnel'
    | '/scenarios/daisy'
    | '/scenarios/fallen'
    | '/scenarios/handoff'
    | '/scenarios/magnetic-attraction'
    | '/scenarios/multi-swarm-handoff'
    | '/scenarios/obstacle-bypass'
    | '/scenarios/predator-evasion'
    | '/scenarios/random-failure'
    | '/scenarios/stake-voting'
    | '/scenarios/thermal-rebalance'
    | '/scenarios/warehouse-restock'
    | '/scenarios/warehouse-restocking'
    | '/dashboard/'
    | '/scenarios/search-rescue/$scenarioSlug'
    | '/scenarios/search-rescue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/demo'
    | '/docs'
    | '/drones'
    | '/features'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/replay'
    | '/safety'
    | '/settings'
    | '/swarm'
    | '/tashi'
    | '/tasks'
    | '/track2-webots'
    | '/vertex'
    | '/vertex-swarm'
    | '/worlds'
    | '/dashboard/$'
    | '/drone/$id'
    | '/drones/$id'
    | '/scenarios/arena-obstacle'
    | '/scenarios/battery-cascade'
    | '/scenarios/blind-handoff'
    | '/scenarios/circular-bypass'
    | '/scenarios/collapsing-tunnel'
    | '/scenarios/daisy'
    | '/scenarios/fallen'
    | '/scenarios/handoff'
    | '/scenarios/magnetic-attraction'
    | '/scenarios/multi-swarm-handoff'
    | '/scenarios/obstacle-bypass'
    | '/scenarios/predator-evasion'
    | '/scenarios/random-failure'
    | '/scenarios/stake-voting'
    | '/scenarios/thermal-rebalance'
    | '/scenarios/warehouse-restock'
    | '/scenarios/warehouse-restocking'
    | '/dashboard'
    | '/scenarios/search-rescue/$scenarioSlug'
    | '/scenarios/search-rescue'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/demo'
    | '/docs'
    | '/drones'
    | '/features'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/replay'
    | '/safety'
    | '/settings'
    | '/swarm'
    | '/tashi'
    | '/tasks'
    | '/track2-webots'
    | '/vertex'
    | '/vertex-swarm'
    | '/worlds'
    | '/dashboard/$'
    | '/drone/$id'
    | '/drones/$id'
    | '/scenarios/arena-obstacle'
    | '/scenarios/battery-cascade'
    | '/scenarios/blind-handoff'
    | '/scenarios/circular-bypass'
    | '/scenarios/collapsing-tunnel'
    | '/scenarios/daisy'
    | '/scenarios/fallen'
    | '/scenarios/handoff'
    | '/scenarios/magnetic-attraction'
    | '/scenarios/multi-swarm-handoff'
    | '/scenarios/obstacle-bypass'
    | '/scenarios/predator-evasion'
    | '/scenarios/random-failure'
    | '/scenarios/stake-voting'
    | '/scenarios/thermal-rebalance'
    | '/scenarios/warehouse-restock'
    | '/scenarios/warehouse-restocking'
    | '/dashboard/'
    | '/scenarios/search-rescue/$scenarioSlug'
    | '/scenarios/search-rescue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRoute
  DronesRoute: typeof DronesRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  NetworkRoute: typeof NetworkRoute
  ReplayRoute: typeof ReplayRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SwarmRoute: typeof SwarmRoute
  TashiRoute: typeof TashiRoute
  TasksRoute: typeof TasksRoute
  Track2WebotsRoute: typeof Track2WebotsRoute
  VertexRoute: typeof VertexRoute
  VertexSwarmRoute: typeof VertexSwarmRoute
  WorldsRoute: typeof WorldsRoute
  DashboardSplatRoute: typeof DashboardSplatRoute
  DroneIdRoute: typeof DroneIdRoute
  ScenariosArenaObstacleRoute: typeof ScenariosArenaObstacleRoute
  ScenariosBatteryCascadeRoute: typeof ScenariosBatteryCascadeRoute
  ScenariosBlindHandoffRoute: typeof ScenariosBlindHandoffRoute
  ScenariosCircularBypassRoute: typeof ScenariosCircularBypassRoute
  ScenariosCollapsingTunnelRoute: typeof ScenariosCollapsingTunnelRoute
  ScenariosDaisyRoute: typeof ScenariosDaisyRoute
  ScenariosFallenRoute: typeof ScenariosFallenRoute
  ScenariosHandoffRoute: typeof ScenariosHandoffRoute
  ScenariosMagneticAttractionRoute: typeof ScenariosMagneticAttractionRoute
  ScenariosMultiSwarmHandoffRoute: typeof ScenariosMultiSwarmHandoffRoute
  ScenariosObstacleBypassRoute: typeof ScenariosObstacleBypassRoute
  ScenariosPredatorEvasionRoute: typeof ScenariosPredatorEvasionRoute
  ScenariosRandomFailureRoute: typeof ScenariosRandomFailureRoute
  ScenariosStakeVotingRoute: typeof ScenariosStakeVotingRoute
  ScenariosThermalRebalanceRoute: typeof ScenariosThermalRebalanceRoute
  ScenariosWarehouseRestockRoute: typeof ScenariosWarehouseRestockRoute
  ScenariosWarehouseRestockingRoute: typeof ScenariosWarehouseRestockingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ScenariosSearchRescueScenarioSlugRoute: typeof ScenariosSearchRescueScenarioSlugRoute
  ScenariosSearchRescueIndexRoute: typeof ScenariosSearchRescueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vertex-swarm': {
      id: '/vertex-swarm'
      path: '/vertex-swarm'
      fullPath: '/vertex-swarm'
      preLoaderRoute: typeof VertexSwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vertex': {
      id: '/vertex'
      path: '/vertex'
      fullPath: '/vertex'
      preLoaderRoute: typeof VertexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track2-webots': {
      id: '/track2-webots'
      path: '/track2-webots'
      fullPath: '/track2-webots'
      preLoaderRoute: typeof Track2WebotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tashi': {
      id: '/tashi'
      path: '/tashi'
      fullPath: '/tashi'
      preLoaderRoute: typeof TashiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swarm': {
      id: '/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof SwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/warehouse-restocking': {
      id: '/scenarios/warehouse-restocking'
      path: '/scenarios/warehouse-restocking'
      fullPath: '/scenarios/warehouse-restocking'
      preLoaderRoute: typeof ScenariosWarehouseRestockingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/warehouse-restock': {
      id: '/scenarios/warehouse-restock'
      path: '/scenarios/warehouse-restock'
      fullPath: '/scenarios/warehouse-restock'
      preLoaderRoute: typeof ScenariosWarehouseRestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/thermal-rebalance': {
      id: '/scenarios/thermal-rebalance'
      path: '/scenarios/thermal-rebalance'
      fullPath: '/scenarios/thermal-rebalance'
      preLoaderRoute: typeof ScenariosThermalRebalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/stake-voting': {
      id: '/scenarios/stake-voting'
      path: '/scenarios/stake-voting'
      fullPath: '/scenarios/stake-voting'
      preLoaderRoute: typeof ScenariosStakeVotingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/random-failure': {
      id: '/scenarios/random-failure'
      path: '/scenarios/random-failure'
      fullPath: '/scenarios/random-failure'
      preLoaderRoute: typeof ScenariosRandomFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/predator-evasion': {
      id: '/scenarios/predator-evasion'
      path: '/scenarios/predator-evasion'
      fullPath: '/scenarios/predator-evasion'
      preLoaderRoute: typeof ScenariosPredatorEvasionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/obstacle-bypass': {
      id: '/scenarios/obstacle-bypass'
      path: '/scenarios/obstacle-bypass'
      fullPath: '/scenarios/obstacle-bypass'
      preLoaderRoute: typeof ScenariosObstacleBypassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/multi-swarm-handoff': {
      id: '/scenarios/multi-swarm-handoff'
      path: '/scenarios/multi-swarm-handoff'
      fullPath: '/scenarios/multi-swarm-handoff'
      preLoaderRoute: typeof ScenariosMultiSwarmHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/magnetic-attraction': {
      id: '/scenarios/magnetic-attraction'
      path: '/scenarios/magnetic-attraction'
      fullPath: '/scenarios/magnetic-attraction'
      preLoaderRoute: typeof ScenariosMagneticAttractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/handoff': {
      id: '/scenarios/handoff'
      path: '/scenarios/handoff'
      fullPath: '/scenarios/handoff'
      preLoaderRoute: typeof ScenariosHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/fallen': {
      id: '/scenarios/fallen'
      path: '/scenarios/fallen'
      fullPath: '/scenarios/fallen'
      preLoaderRoute: typeof ScenariosFallenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/daisy': {
      id: '/scenarios/daisy'
      path: '/scenarios/daisy'
      fullPath: '/scenarios/daisy'
      preLoaderRoute: typeof ScenariosDaisyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/collapsing-tunnel': {
      id: '/scenarios/collapsing-tunnel'
      path: '/scenarios/collapsing-tunnel'
      fullPath: '/scenarios/collapsing-tunnel'
      preLoaderRoute: typeof ScenariosCollapsingTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/circular-bypass': {
      id: '/scenarios/circular-bypass'
      path: '/scenarios/circular-bypass'
      fullPath: '/scenarios/circular-bypass'
      preLoaderRoute: typeof ScenariosCircularBypassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/blind-handoff': {
      id: '/scenarios/blind-handoff'
      path: '/scenarios/blind-handoff'
      fullPath: '/scenarios/blind-handoff'
      preLoaderRoute: typeof ScenariosBlindHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/battery-cascade': {
      id: '/scenarios/battery-cascade'
      path: '/scenarios/battery-cascade'
      fullPath: '/scenarios/battery-cascade'
      preLoaderRoute: typeof ScenariosBatteryCascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/arena-obstacle': {
      id: '/scenarios/arena-obstacle'
      path: '/scenarios/arena-obstacle'
      fullPath: '/scenarios/arena-obstacle'
      preLoaderRoute: typeof ScenariosArenaObstacleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones/$id': {
      id: '/drones/$id'
      path: '/$id'
      fullPath: '/drones/$id'
      preLoaderRoute: typeof DronesIdRouteImport
      parentRoute: typeof DronesRoute
    }
    '/drone/$id': {
      id: '/drone/$id'
      path: '/drone/$id'
      fullPath: '/drone/$id'
      preLoaderRoute: typeof DroneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/dashboard/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/search-rescue/': {
      id: '/scenarios/search-rescue/'
      path: '/scenarios/search-rescue'
      fullPath: '/scenarios/search-rescue/'
      preLoaderRoute: typeof ScenariosSearchRescueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/search-rescue/$scenarioSlug': {
      id: '/scenarios/search-rescue/$scenarioSlug'
      path: '/scenarios/search-rescue/$scenarioSlug'
      fullPath: '/scenarios/search-rescue/$scenarioSlug'
      preLoaderRoute: typeof ScenariosSearchRescueScenarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DronesRouteChildren {
  DronesIdRoute: typeof DronesIdRoute
}

const DronesRouteChildren: DronesRouteChildren = {
  DronesIdRoute: DronesIdRoute,
}

const DronesRouteWithChildren =
  DronesRoute._addFileChildren(DronesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRoute,
  DronesRoute: DronesRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  NetworkRoute: NetworkRoute,
  ReplayRoute: ReplayRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SwarmRoute: SwarmRoute,
  TashiRoute: TashiRoute,
  TasksRoute: TasksRoute,
  Track2WebotsRoute: Track2WebotsRoute,
  VertexRoute: VertexRoute,
  VertexSwarmRoute: VertexSwarmRoute,
  WorldsRoute: WorldsRoute,
  DashboardSplatRoute: DashboardSplatRoute,
  DroneIdRoute: DroneIdRoute,
  ScenariosArenaObstacleRoute: ScenariosArenaObstacleRoute,
  ScenariosBatteryCascadeRoute: ScenariosBatteryCascadeRoute,
  ScenariosBlindHandoffRoute: ScenariosBlindHandoffRoute,
  ScenariosCircularBypassRoute: ScenariosCircularBypassRoute,
  ScenariosCollapsingTunnelRoute: ScenariosCollapsingTunnelRoute,
  ScenariosDaisyRoute: ScenariosDaisyRoute,
  ScenariosFallenRoute: ScenariosFallenRoute,
  ScenariosHandoffRoute: ScenariosHandoffRoute,
  ScenariosMagneticAttractionRoute: ScenariosMagneticAttractionRoute,
  ScenariosMultiSwarmHandoffRoute: ScenariosMultiSwarmHandoffRoute,
  ScenariosObstacleBypassRoute: ScenariosObstacleBypassRoute,
  ScenariosPredatorEvasionRoute: ScenariosPredatorEvasionRoute,
  ScenariosRandomFailureRoute: ScenariosRandomFailureRoute,
  ScenariosStakeVotingRoute: ScenariosStakeVotingRoute,
  ScenariosThermalRebalanceRoute: ScenariosThermalRebalanceRoute,
  ScenariosWarehouseRestockRoute: ScenariosWarehouseRestockRoute,
  ScenariosWarehouseRestockingRoute: ScenariosWarehouseRestockingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ScenariosSearchRescueScenarioSlugRoute:
    ScenariosSearchRescueScenarioSlugRoute,
  ScenariosSearchRescueIndexRoute: ScenariosSearchRescueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
